#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。

[project]
id = "sevenc-nanashi.ffmpeg-aui2"
name = "ffmpeg.aui2"
version = "0.1.0"

[build_group]
download_ffmpeg = "ruby download_ffmpeg.rb"

[development]
aviutl2_version = "latest"
catalog_dependencies = ["Mr-Ojii.L-SMASH-Works"]

[preview]
catalog_dependencies = [
  "Mr-Ojii.L-SMASH-Works",
  "sevenc-nanashi.aviutl2-rs.rusty_statistics"
]

[artifacts.fix_hdr]
destination = "Script/HDR修正.anm2"
source = "./fix_hdr.lua"

[artifacts.fix_hdr.profiles.release]
# 需要があれば配布するかも？
enabled = false

[artifacts.bootstrapper]
destination = "Plugin/ffmpeg-aui2/ffmpeg.aui2"

[artifacts.bootstrapper.profiles.debug]
build = "cargo build -p ffmpeg_aui2_bootstrapper"
source = "target/debug/ffmpeg_aui2_bootstrapper.dll"

[artifacts.bootstrapper.profiles.release]
build = "cargo build --release -p ffmpeg_aui2_bootstrapper"
source = "target/release/ffmpeg_aui2_bootstrapper.dll"

[artifacts.core]
destination = "Plugin/ffmpeg-aui2/ffmpeg_aui2_core.dll"

[artifacts.core.profiles.debug]
build = "cargo build -p ffmpeg_aui2"
source = "target/debug/ffmpeg_aui2.dll"

[artifacts.core.profiles.release]
build = "cargo build --release -p ffmpeg_aui2"
source = "target/release/ffmpeg_aui2.dll"

# TODO: aviutl2-cliにglobコピーを実装する
[artifacts.dependencies_avcodec-62]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/avcodec-62.dll"
source = "./ffmpeg/bin/avcodec-62.dll"

[artifacts.dependencies_avformat-62]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/avformat-62.dll"
source = "./ffmpeg/bin/avformat-62.dll"

[artifacts.dependencies_avfilter-11]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/avfilter-11.dll"
source = "./ffmpeg/bin/avfilter-11.dll"

[artifacts.dependencies_avdevice-62]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/avdevice-62.dll"
source = "./ffmpeg/bin/avdevice-62.dll"

[artifacts.dependencies_avutil-60]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/avutil-60.dll"
source = "./ffmpeg/bin/avutil-60.dll"

[artifacts.dependencies_swscale-9]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/swscale-9.dll"
source = "./ffmpeg/bin/swscale-9.dll"

[artifacts.dependencies_swresample-6]
build = { group = "download_ffmpeg" }
destination = "Plugin/ffmpeg-aui2/dependencies/swresample-6.dll"
source = "./ffmpeg/bin/swresample-6.dll"
