[plugins]
cargo-prebuilt = "https://github.com/sevenc-nanashi/mise-cargo-prebuilt"

[tools]
"github:sevenc-nanashi/aviutl2-cli" = { version = "0.9.0-preview.0", bin = "au2.exe" }
ruby = "latest"
"github:EmbarkStudios/cargo-about" = { version = "latest" }
"cargo-prebuilt:cargo-edit" = "latest"
