; ffmpeg.aui2の設定
; 設定の変更後はAviUtl2を再起動してください。
; リセットするには、このファイルを削除した後にAviUtl2を起動してください。

[general]
; ログレベル。
; trace、debug、info、warn、errorから選択してください。
log_level = info

; デバッグ用に、読みやすいインデックスを生成します。
json_index = false

; ハードウェアアクセラレーション。
; none、auto、d3d11va、dxva2、cudaから選択してください。
; autoはd3d11vaを試し、失敗した場合はdxva2を試します。
hwaccel = none

; FPSの計算方法。
; metadata: 動画のメタデータのFPSをそのまま使用します。
; real: 動画の実時間/フレーム数から計算します。
fps_mode = real

; FPSの精度。fps_mode = real のときのみ使用されます。
; 0の場合、整数に丸めます。
; 1以上の場合、10^(-fps_precision)の精度で丸めます。
fps_precision = 3

; インデックスのキャッシュを概算で行うかどうか。
; trueの場合、ファイルサイズ・更新日時・先頭/末尾256KBのみでハッシュを計算します。
; 大容量ファイルのオープンが高速になりますが、ファイルが変更されても検出できない場合があります。
rough_cache = true

; ffmpeg.aui2は、動画を読み込むときに自動的に少し先まで読み込んでおく機能があります。
; この機能は、動画の再生を速くすることができますが、使用するメモリ量も増えます。
;
; 読み込むフレーム数はprefetch_buffer_mb、prefetch_total_buffer_mb、prefetch_framesの3つの設定から算出された
; フレームのうち、最小のフレーム数になります。
;
;
; 先読みに使用するバッファサイズ (MB単位)。
prefetch_buffer_mb = 32

; すべての動画での先読みの合計バッファサイズ (MB単位)。
prefetch_total_buffer_mb = 512

; 先読みするフレーム数。
prefetch_frames = 10
