; ffmpeg.aui2の設定
; 設定の変更後はAviUtl2を再起動してください。
; リセットするには、このファイルを削除してください。

[general]
; ログレベル。
; trace、debug、info、warn、errorから選択してください。
log_level = info

; デバッグ用に、読みやすいインデックスを生成します。
json_index = false

; 動画プリフェッチに使用するバッファサイズ (MB単位)。
prefetch_buffer_mb = 32

; ハードウェアアクセラレーション。
; none、auto、d3d11va、dxva2、cudaから選択してください。
; autoはd3d11vaを試し、失敗した場合はdxva2を試します。
hwaccel = none
